import React from 'react';
import { Brain, FileWarning, LineChart as ChartLineUp, RefreshCw, Lightbulb, BarChart, DownloadCloud, ArrowUpRight } from 'lucide-react';

const AIInsights = () => {
  return (
    <div className="animate-[fadeIn_0.3s_ease-in-out]">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-6">
        <div className="flex items-center">
          <h1 className="text-2xl font-bold text-gray-800">AI Insights</h1>
          <span className="ml-2 text-xs bg-purple-100 text-purple-800 px-2 py-1 rounded-full whitespace-nowrap">
            Powered by VerityONE AI
          </span>
        </div>
        <div className="flex gap-3 w-full sm:w-auto">
          <button className="flex items-center gap-2 px-4 py-2 bg-gray-100 text-gray-700 rounded-md hover:bg-gray-200 transition-colors w-full sm:w-auto justify-center">
            <RefreshCw size={16} />
            <span>Refresh</span>
          </button>
          <button className="flex items-center gap-2 px-4 py-2 bg-purple-600 text-white rounded-md hover:bg-purple-700 transition-colors w-full sm:w-auto justify-center">
            <DownloadCloud size={16} />
            <span>Export Report</span>
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-6">
        <div className="bg-white rounded-lg shadow p-6 border border-gray-200">
          <div className="flex items-center justify-between mb-4">
            <div className="p-2 bg-purple-100 rounded-lg">
              <Brain className="text-purple-600" size={24} />
            </div>
            <span className="text-sm text-green-600 flex items-center">
              +24% <ArrowUpRight size={14} className="ml-1" />
            </span>
          </div>
          <h3 className="text-lg font-semibold text-gray-800 mb-1">Test Coverage Analysis</h3>
          <p className="text-sm text-gray-600 mb-4">AI-powered analysis of test coverage and recommendations</p>
          <div className="flex items-center justify-between">
            <span className="text-2xl font-bold text-gray-900">87%</span>
            <button className="text-purple-600 text-sm hover:text-purple-800">View Details →</button>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow p-6 border border-gray-200">
          <div className="flex items-center justify-between mb-4">
            <div className="p-2 bg-blue-100 rounded-lg">
              <FileWarning className="text-blue-600" size={24} />
            </div>
            <span className="text-sm text-red-600 flex items-center">
              +8% <ArrowUpRight size={14} className="ml-1" />
            </span>
          </div>
          <h3 className="text-lg font-semibold text-gray-800 mb-1">Risk Assessment</h3>
          <p className="text-sm text-gray-600 mb-4">Potential risks and vulnerabilities detected</p>
          <div className="flex items-center justify-between">
            <span className="text-2xl font-bold text-gray-900">12</span>
            <button className="text-blue-600 text-sm hover:text-blue-800">View Details →</button>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow p-6 border border-gray-200">
          <div className="flex items-center justify-between mb-4">
            <div className="p-2 bg-green-100 rounded-lg">
              <ChartLineUp className="text-green-600" size={24} />
            </div>
            <span className="text-sm text-green-600 flex items-center">
              +15% <ArrowUpRight size={14} className="ml-1" />
            </span>
          </div>
          <h3 className="text-lg font-semibold text-gray-800 mb-1">Performance Metrics</h3>
          <p className="text-sm text-gray-600 mb-4">AI-analyzed performance trends and insights</p>
          <div className="flex items-center justify-between">
            <span className="text-2xl font-bold text-gray-900">94%</span>
            <button className="text-green-600 text-sm hover:text-green-800">View Details →</button>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 bg-white rounded-lg shadow border border-gray-200">
          <div className="p-4 border-b border-gray-200">
            <h2 className="text-lg font-semibold text-gray-800">AI-Generated Test Cases</h2>
            <p className="text-sm text-gray-600">Recent test cases generated by AI based on requirements</p>
          </div>
          <div className="p-4">
            <div className="space-y-4">
              {[1, 2, 3, 4].map((item) => (
                <div key={item} className="border border-gray-200 rounded-lg p-4">
                  <div className="flex items-start justify-between">
                    <div>
                      <h3 className="font-medium text-gray-800">User Authentication Flow Test #{item}</h3>
                      <p className="text-sm text-gray-600 mt-1">Generated from user stories and requirements analysis</p>
                    </div>
                    <span className="px-2 py-1 text-xs bg-green-100 text-green-800 rounded-full">98% Confidence</span>
                  </div>
                  <div className="mt-3 flex items-center gap-4">
                    <button className="text-sm text-blue-600 hover:text-blue-800">View Details</button>
                    <button className="text-sm text-purple-600 hover:text-purple-800">Generate Similar</button>
                    <button className="text-sm text-gray-600 hover:text-gray-800">Export</button>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow border border-gray-200">
          <div className="p-4 border-b border-gray-200">
            <h2 className="text-lg font-semibold text-gray-800">AI Recommendations</h2>
            <p className="text-sm text-gray-600">Smart suggestions for improving test coverage</p>
          </div>
          <div className="p-4">
            <div className="space-y-4">
              {[1, 2, 3, 4].map((item) => (
                <div key={item} className="flex items-start gap-3">
                  <div className="p-2 bg-purple-100 rounded-lg">
                    <Lightbulb className="text-purple-600" size={16} />
                  </div>
                  <div>
                    <h4 className="text-sm font-medium text-gray-800">Add API Response Validation</h4>
                    <p className="text-xs text-gray-600 mt-1">
                      Consider adding comprehensive validation for API responses in the payment module
                    </p>
                    <div className="mt-2 flex items-center gap-2">
                      <span className="text-xs text-purple-600">92% relevant</span>
                      <button className="text-xs text-blue-600 hover:text-blue-800">
                        Generate Tests →
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AIInsights;